## Introduction to Pandas

## What is Pandas?
**Pandas** is a Python library for working with tabular (spreadsheet-like) data.

- **Series:** a single labeled column of data (1D).
- **DataFrame:** a full table of rows and columns (2D), like an Excel sheet.
- Built on top of NumPy, so it's fast, and it adds row/column labels and easy file reading.
- Used for loading, cleaning, filtering, sorting and summarizing data before ML training.

In [1]:
# Series
import pandas as pd

s = pd.Series([10, 20, 30, 40])
print(s)

0    10
1    20
2    30
3    40
dtype: int64

In [2]:
print(s[0])        # 10
print(s[2])        # 30
print(s[1:3])       # index 1 and 2

10
30
1    20
2    30
dtype: int64

In [3]:
marks = pd.Series([85, 90, 78], index=["Asha", "Ravi", "Meena"])
print(marks)
print(marks["Ravi"])    # 90

Asha     85
Ravi     90
Meena    78
dtype: int64
90

In [4]:
# DataFrame
data = {
    "name":   ["Asha", "Ravi", "Meena", "Kiran"],
    "age":    [22, 25, 23, 28],
    "dept":   ["IT", "HR", "IT", "Sales"],
    "salary": [30000, 28000, 32000, 40000],
}
df = pd.DataFrame(data)
df

    name  age   dept  salary
0   Asha   22     IT   30000
1   Ravi   25     HR   28000
2  Meena   23     IT   32000
3  Kiran   28  Sales   40000

In [5]:
df2 = pd.DataFrame([[1, "A"], [2, "B"]], columns=["id", "grade"])
df2

   id grade
0   1     A
1   2     B

In [17]:
print(1+1)

2

In [6]:
df.to_csv("employees.csv", index=False)
df3 = pd.read_csv("employees.csv")
df3

    name  age   dept  salary
0   Asha   22     IT   30000
1   Ravi   25     HR   28000
2  Meena   23     IT   32000
3  Kiran   28  Sales   40000

In [8]:
print(df3.head(2))      # first 2 rows
print(df3.tail(2))      # last 2 rows
df3.info()               # columns, types, non-null counts
print(df3.describe())   # statistics for numeric columns

   name  age dept  salary
0  Asha   22   IT   30000
1  Ravi   25   HR   28000
    name  age   dept  salary
2  Meena   23     IT   32000
3  Kiran   28  Sales   40000
<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    4 non-null      str
 1   age     4 non-null      int64
 2   dept    4 non-null      str
 3   salary  4 non-null      int64
dtypes: int64(2), str(2)
memory usage: 260.0 bytes
             age        salary
count   4.000000      4.000000
mean   24.500000  32500.000000
std     2.645751   5259.911279
min    22.000000  28000.000000
25%    22.750000  29500.000000
50%    24.000000  31000.000000
75%    25.750000  34000.000000
max    28.000000  40000.000000

In [9]:
print("Shape:", df3.shape)
print("Columns:", df3.columns.tolist())
print(df3.dtypes)

Shape: (4, 4)
Columns: ['name', 'age', 'dept', 'salary']
name        str
age       int64
dept        str
salary    int64
dtype: object

In [10]:
print(df3["name"])

0     Asha
1     Ravi
2    Meena
3    Kiran
Name: name, dtype: str

In [11]:
print(df3.loc[1])                       # row with index label 1
print(df3.loc[1, "name"])               # single value -> "Ravi"
print(df3.loc[0:2, ["name", "age"]])    # rows 0-2, chosen columns

name       Ravi
age          25
dept         HR
salary    28000
Name: 1, dtype: object
Ravi
    name  age
0   Asha   22
1   Ravi   25
2  Meena   23

In [12]:
print(df3.iloc[1])          # 2nd row by position
print(df3.iloc[0:2, 0:2])   # first 2 rows, first 2 columns
print(df3.iloc[-1])         # last row

name       Ravi
age          25
dept         HR
salary    28000
Name: 1, dtype: object
   name  age
0  Asha   22
1  Ravi   25
name      Kiran
age          28
dept      Sales
salary    40000
Name: 3, dtype: object

In [13]:
print(df3[df3["salary"] > 28000])

    name  age   dept  salary
0   Asha   22     IT   30000
2  Meena   23     IT   32000
3  Kiran   28  Sales   40000

In [14]:
print(df3[(df3["dept"] == "IT") & (df3["age"] > 22)])

    name  age dept  salary
2  Meena   23   IT   32000

In [15]:
print(df3[df3["dept"].isin(["IT", "HR"])])

    name  age dept  salary
0   Asha   22   IT   30000
1   Ravi   25   HR   28000
2  Meena   23   IT   32000

In [16]:
# Sorting
print(df3.sort_values("salary"))                       # ascending
print(df3.sort_values("salary", ascending=False))      # descending
print(df3.sort_values(["dept", "salary"]))              # sort by two columns

    name  age   dept  salary
1   Ravi   25     HR   28000
0   Asha   22     IT   30000
2  Meena   23     IT   32000
3  Kiran   28  Sales   40000
    name  age   dept  salary
3  Kiran   28  Sales   40000
2  Meena   23     IT   32000
0   Asha   22     IT   30000
1   Ravi   25     HR   28000
    name  age   dept  salary
1   Ravi   25     HR   28000
0   Asha   22     IT   30000
2  Meena   23     IT   32000
3  Kiran   28  Sales   40000